// flow-typed signature: 0b53b1f0368f50c68ce376a2cd2a8ded
// flow-typed version: <<STUB>>/react-big-calendar_v^0.17.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-big-calendar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-big-calendar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-big-calendar/lib/addons/dragAndDrop/backgroundWrapper' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/addons/dragAndDrop/DraggableEventWrapper' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/addons/dragAndDrop/index' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/Agenda' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/BackgroundCells' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/BackgroundWrapper' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/Calendar' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/DateContentRow' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/DateHeader' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/Day' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/DayColumn' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/EventCell' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/EventEndingRow' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/EventRow' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/EventRowMixin' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/EventWrapper' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/formats' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/Header' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/index' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/localizer' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/localizers/globalize' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/localizers/moment' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/localizers/oldGlobalize' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/Month' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/Popup' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/Selection' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/TimeColumn' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/TimeGrid' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/TimeSlot' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/TimeSlotGroup' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/Toolbar' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/utils/accessors' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/utils/constants' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/utils/dates' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/utils/dayViewLayout' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/utils/eventLevels' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/utils/helpers' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/utils/messages' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/utils/move' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/utils/propTypes' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/utils/selection' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/Views' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/Week' {
  declare module.exports: any;
}

declare module 'react-big-calendar/lib/WorkWeek' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-big-calendar/lib/addons/dragAndDrop/backgroundWrapper.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/addons/dragAndDrop/backgroundWrapper'>;
}
declare module 'react-big-calendar/lib/addons/dragAndDrop/DraggableEventWrapper.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/addons/dragAndDrop/DraggableEventWrapper'>;
}
declare module 'react-big-calendar/lib/addons/dragAndDrop/index.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/addons/dragAndDrop/index'>;
}
declare module 'react-big-calendar/lib/Agenda.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/Agenda'>;
}
declare module 'react-big-calendar/lib/BackgroundCells.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/BackgroundCells'>;
}
declare module 'react-big-calendar/lib/BackgroundWrapper.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/BackgroundWrapper'>;
}
declare module 'react-big-calendar/lib/Calendar.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/Calendar'>;
}
declare module 'react-big-calendar/lib/DateContentRow.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/DateContentRow'>;
}
declare module 'react-big-calendar/lib/DateHeader.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/DateHeader'>;
}
declare module 'react-big-calendar/lib/Day.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/Day'>;
}
declare module 'react-big-calendar/lib/DayColumn.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/DayColumn'>;
}
declare module 'react-big-calendar/lib/EventCell.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/EventCell'>;
}
declare module 'react-big-calendar/lib/EventEndingRow.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/EventEndingRow'>;
}
declare module 'react-big-calendar/lib/EventRow.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/EventRow'>;
}
declare module 'react-big-calendar/lib/EventRowMixin.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/EventRowMixin'>;
}
declare module 'react-big-calendar/lib/EventWrapper.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/EventWrapper'>;
}
declare module 'react-big-calendar/lib/formats.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/formats'>;
}
declare module 'react-big-calendar/lib/Header.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/Header'>;
}
declare module 'react-big-calendar/lib/index.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/index'>;
}
declare module 'react-big-calendar/lib/localizer.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/localizer'>;
}
declare module 'react-big-calendar/lib/localizers/globalize.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/localizers/globalize'>;
}
declare module 'react-big-calendar/lib/localizers/moment.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/localizers/moment'>;
}
declare module 'react-big-calendar/lib/localizers/oldGlobalize.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/localizers/oldGlobalize'>;
}
declare module 'react-big-calendar/lib/Month.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/Month'>;
}
declare module 'react-big-calendar/lib/Popup.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/Popup'>;
}
declare module 'react-big-calendar/lib/Selection.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/Selection'>;
}
declare module 'react-big-calendar/lib/TimeColumn.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/TimeColumn'>;
}
declare module 'react-big-calendar/lib/TimeGrid.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/TimeGrid'>;
}
declare module 'react-big-calendar/lib/TimeSlot.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/TimeSlot'>;
}
declare module 'react-big-calendar/lib/TimeSlotGroup.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/TimeSlotGroup'>;
}
declare module 'react-big-calendar/lib/Toolbar.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/Toolbar'>;
}
declare module 'react-big-calendar/lib/utils/accessors.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/utils/accessors'>;
}
declare module 'react-big-calendar/lib/utils/constants.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/utils/constants'>;
}
declare module 'react-big-calendar/lib/utils/dates.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/utils/dates'>;
}
declare module 'react-big-calendar/lib/utils/dayViewLayout.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/utils/dayViewLayout'>;
}
declare module 'react-big-calendar/lib/utils/eventLevels.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/utils/eventLevels'>;
}
declare module 'react-big-calendar/lib/utils/helpers.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/utils/helpers'>;
}
declare module 'react-big-calendar/lib/utils/messages.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/utils/messages'>;
}
declare module 'react-big-calendar/lib/utils/move.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/utils/move'>;
}
declare module 'react-big-calendar/lib/utils/propTypes.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/utils/propTypes'>;
}
declare module 'react-big-calendar/lib/utils/selection.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/utils/selection'>;
}
declare module 'react-big-calendar/lib/Views.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/Views'>;
}
declare module 'react-big-calendar/lib/Week.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/Week'>;
}
declare module 'react-big-calendar/lib/WorkWeek.js' {
  declare module.exports: $Exports<'react-big-calendar/lib/WorkWeek'>;
}
