// flow-typed signature: 4045e619e3a1565296da3027975e66b7
// flow-typed version: <<STUB>>/react-facebook-player_v^0.1.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-facebook-player'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-facebook-player' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-facebook-player/dist/FacebookPlayer' {
  declare module.exports: any;
}

declare module 'react-facebook-player/test/FacebookPlayer-test' {
  declare module.exports: any;
}

declare module 'react-facebook-player/test/helpers/fullRender' {
  declare module.exports: any;
}

declare module 'react-facebook-player/test/helpers/setupEnvironment' {
  declare module.exports: any;
}

declare module 'react-facebook-player/test/helpers/setupPlayer' {
  declare module.exports: any;
}

declare module 'react-facebook-player/test/helpers/shallowRender' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-facebook-player/dist/FacebookPlayer.js' {
  declare module.exports: $Exports<'react-facebook-player/dist/FacebookPlayer'>;
}
declare module 'react-facebook-player/test/FacebookPlayer-test.js' {
  declare module.exports: $Exports<'react-facebook-player/test/FacebookPlayer-test'>;
}
declare module 'react-facebook-player/test/helpers/fullRender.js' {
  declare module.exports: $Exports<'react-facebook-player/test/helpers/fullRender'>;
}
declare module 'react-facebook-player/test/helpers/setupEnvironment.js' {
  declare module.exports: $Exports<'react-facebook-player/test/helpers/setupEnvironment'>;
}
declare module 'react-facebook-player/test/helpers/setupPlayer.js' {
  declare module.exports: $Exports<'react-facebook-player/test/helpers/setupPlayer'>;
}
declare module 'react-facebook-player/test/helpers/shallowRender.js' {
  declare module.exports: $Exports<'react-facebook-player/test/helpers/shallowRender'>;
}
