export enum NotificationType {
  NEW_EVENT = "NEW_EVENT",
  NEW_GROUP_POST = "NEW_GROUP_POST",
  NEW_EVENT_POST = "NEW_EVENT_POST",
  NEW_CLUB_POST = "NEW_CLUB_POST",
  NEW_STUDENT_POST = "NEW_STUDENT_POST",
}