name: CI Workflow for PR

on:
  pull_request:
    types: [opened]
    branches:
      - master

jobs:
  comment:
    name: Comment PR
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate message file
        run: |
          export BRANCH_HASH=$(git rev-parse --abbrev-ref HEAD | md5sum | awk '{print $1}')
          printf "Hello :wave:\n\nYou can preview your changes at [this link](https://$BRANCH_HASH.dev-github-pr.iseplife.fr)" > message.txt

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: message.txt
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
