name: CI Workflow for PR

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  remove-s3-pr-preview:
    name: Deploy to S3 for PR Preview
    runs-on: ubuntu-latest
    needs: pr-prebuild
    if: github.ref != 'refs/heads/master'
    steps:
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-west-3' # Update region if necessary

      - name: Deploy to S3
        run: |
          export BRANCH_HASH=$(git rev-parse --abbrev-ref HEAD | md5sum | awk '{print $1}')
          aws s3 rm s3://iseplife-github-prs/$BRANCH_HASH --recursive
